from pathlib import Path
p=Path('/mnt/data/work/app/static/index.html'); s=p.read_text(); s=s.replace('<button data-page="users" class="manager-only">♙ <span>Tài khoản</span></button>', '<button data-page="users" class="manager-only">♙ <span>Tài khoản</span></button>\n      <button data-page="activity" class="manager-only">⌁ <span>Nhật ký hoạt động</span></button>'); p.write_text(s)
p=Path('/mnt/data/work/app/static/app.js'); s=p.read_text()
s=s.replace('settings:"Cài đặt doanh nghiệp"};','settings:"Cài đặt doanh nghiệp",activity:"Nhật ký hoạt động"};')
# safer vehicle delete
old='''    # Xóa các dữ liệu phụ thuộc để không vi phạm khóa ngoại.\n    db.query(Ticket).filter(Ticket.vehicle_id == vehicle_id).delete(synchronize_session=False)\n    db.query(ParkingRecord).filter(ParkingRecord.vehicle_id == vehicle_id).delete(synchronize_session=False)\n    plate = vehicle.license_plate\n    db.delete(vehicle)\n    db.commit()\n    return {"message": f"Đã xóa xe {plate} và lịch sử liên quan"}'''
new='''    has_history = db.query(ParkingRecord).filter(ParkingRecord.vehicle_id == vehicle_id).first()\n    if has_history:\n        raise HTTPException(409, "Xe đã có lịch sử gửi xe. Không xóa để bảo toàn dữ liệu; chỉ có thể xóa xe chưa phát sinh lịch sử.")\n    db.query(Ticket).filter(Ticket.vehicle_id == vehicle_id).delete(synchronize_session=False)\n    plate = vehicle.license_plate\n    db.delete(vehicle)\n    audit(db, user, "DELETE_VEHICLE", f"Xóa phương tiện {plate}")\n    db.commit()\n    return {"message": f"Đã xóa xe {plate}"}'''
# This block is in main.py not js
p2=Path('/mnt/data/work/app/main.py'); m=p2.read_text(); m=m.replace(old,new); p2.write_text(m)
# Add dashboard enhanced cards/activity and duration updater by replacing card string segment
oldcards='''<div class="cards"><div class="card"><div class="label">XE ĐANG GỬI</div><div class="metric">${d.active_vehicles}</div><div class="trend">● Đang vận hành</div></div><div class="card"><div class="label">CHỖ TRỐNG</div><div class="metric">${d.empty}</div><div class="trend">${d.total_slots} tổng vị trí</div></div><div class="card"><div class="label">TỶ LỆ LẤP ĐẦY</div><div class="metric">${d.occupancy_rate}%</div><div class="trend">Theo dữ liệu thực tế</div></div><div class="card"><div class="label">DOANH THU</div><div class="metric">${money(d.revenue)}</div><div class="trend">${d.closed_records} lượt hoàn tất</div></div><div class="card"><div class="label">GIỜ CAO ĐIỂM</div><div class="metric" style="font-size:21px">${d.peak_hour}</div><div class="trend">AI có thể phân tích</div></div></div>'''
newcards='''<div class="cards"><div class="card"><div class="label">XE ĐANG GỬI</div><div class="metric">${d.active_vehicles}</div><div class="trend">● Đang vận hành</div></div><div class="card"><div class="label">Ô TRỐNG</div><div class="metric">${d.empty}</div><div class="trend">${d.total_slots} tổng vị trí</div></div><div class="card"><div class="label">LƯỢT XE VÀO HÔM NAY</div><div class="metric">${d.today_checkins}</div><div class="trend">Dữ liệu thực tế</div></div><div class="card"><div class="label">LƯỢT XE RA HÔM NAY</div><div class="metric">${d.today_checkouts}</div><div class="trend">Đã hoàn tất</div></div><div class="card"><div class="label">DOANH THU HÔM NAY</div><div class="metric">${money(d.today_revenue)}</div><div class="trend">${d.closed_records} lượt hoàn tất toàn hệ thống</div></div><div class="card"><div class="label">TỶ LỆ LẤP ĐẦY</div><div class="metric">${d.occupancy_rate}%</div><div class="trend">Cao điểm ${d.peak_hour}</div></div></div>'''
s=s.replace(oldcards,newcards)
# dashboard call analytics/activity
s=s.replace('''dashboard:async()=>{let d=await api("/api/dashboard"),s=await api("/api/slots"),a=await api("/api/active");window.__latestSlots=s;''','''dashboard:async()=>{let d=await api("/api/dashboard"),an=await api("/api/analytics"),s=await api("/api/slots"),a=await api("/api/active"),log=await api("/api/activity?limit=8");d={...d,...an};window.__latestSlots=s;''')
# insert activity panel before closing dashboard template's active panel. Find exact end fragment
needle='''</div></div>`;wireMapInteractions()},'''
replacement='''</div></div><div class="panel"><div class="panel-head"><div><h3>Nhật ký hoạt động gần đây</h3><span class="muted">Theo dõi thao tác quản trị và xe vào/ra</span></div><button class="btn" data-page="activity" id="openActivity">Xem tất cả</button></div><div class="activity-list">${log.map(x=>`<div class="activity-item"><div><b>${x.action}</b><div class="muted">${x.detail}</div></div><span class="muted">${dt(x.created_at)} · ${x.username}</span></div>`).join("")||'<div class="empty-state">Chưa có nhật ký</div>'}</div></div></div>`;document.getElementById("openActivity")?.addEventListener("click",()=>navigate("activity"));wireMapInteractions()},'''
s=s.replace(needle,replacement,1)
# add activity page before settings page
marker='window.pages.settings=async()=>'
activity='''window.pages.activity=async()=>{const log=await api('/api/activity?limit=100');$('#content').innerHTML=`<div class="panel"><div class="panel-head"><div><h3>Nhật ký hoạt động</h3><span class="muted">100 thao tác gần nhất · dữ liệu lưu trong PostgreSQL</span></div><span class="pill green">AUDIT LOG</span></div><div class="activity-list">${log.map(x=>`<div class="activity-item"><div><b>${x.action}</b><div class="muted">${x.detail}</div></div><span class="muted">${dt(x.created_at)} · ${x.username}</span></div>`).join('')||'<div class="empty-state">Chưa có dữ liệu</div>'}</div></div>`}\n'''
s=s.replace(marker,activity+marker)
# Add styles
p.write_text(s)
css=Path('/mnt/data/work/app/static/style.css'); c=css.read_text(); c += '''\n\n/* PRO OPERATIONS / AUDIT */\n.activity-list{display:flex;flex-direction:column;gap:0}.activity-item{display:flex;justify-content:space-between;gap:18px;padding:13px 0;border-bottom:1px solid var(--line);align-items:center}.activity-item:last-child{border-bottom:0}.activity-item b{font-size:13px;letter-spacing:.02em}.activity-item .muted{font-size:12px;margin-top:3px}@media(max-width:760px){.activity-item{align-items:flex-start;flex-direction:column;gap:5px}.activity-item>span{white-space:normal}.cards{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:340px){.cards{grid-template-columns:1fr!important}}\n'''; css.write_text(c)
