from pathlib import Path
p=Path('/mnt/data/work/app/main.py')
s=p.read_text()
s=s.replace('from sqlalchemy import create_engine, Column, Integer, String, Float, Boolean, DateTime, ForeignKey, func', 'from sqlalchemy import create_engine, Column, Integer, String, Float, Boolean, DateTime, ForeignKey, func, Text')
needle='''class ParkingRecord(Base):\n    __tablename__ = "parking_records"\n    id = Column(Integer, primary_key=True)\n    vehicle_id = Column(Integer, ForeignKey("vehicles.id"), nullable=False)\n    slot_id = Column(Integer, ForeignKey("parking_slots.id"), nullable=False)\n    time_in = Column(DateTime, nullable=False)\n    time_out = Column(DateTime, nullable=True)\n    fee = Column(Float, nullable=True)\n'''
insert=needle+'''\nclass AuditLog(Base):\n    __tablename__ = "audit_logs"\n    id = Column(Integer, primary_key=True)\n    user_id = Column(Integer, ForeignKey("users.id"), nullable=True)\n    action = Column(String(80), nullable=False)\n    detail = Column(Text, nullable=False, default="")\n    created_at = Column(DateTime, nullable=False, default=now_vn)\n'''
s=s.replace(needle,insert)
# add helper before seed
needle='def seed():\n'
helper='''def audit(db: Session, user: Optional[User], action: str, detail: str = ""):\n    db.add(AuditLog(user_id=user.id if user else None, action=action, detail=detail[:1000], created_at=now_vn()))\n\ndef infer_vehicle_type(plate: str) -> str:\n    import re\n    p = re.sub(r"[^A-Z0-9]", "", plate.upper())\n    # Vietnamese motorcycle formats requested by the operator: 29B1..., 29AD..., etc.\n    if re.match(r"^\\d{2}[A-Z]{1,2}\\d", p) and not re.match(r"^\\d{2}A\\d", p):\n        return "Xe máy"\n    if re.match(r"^\\d{2}[A-Z]\\d", p):\n        return "Ô tô"\n    if re.match(r"^\\d{2}[A-Z]{2}", p):\n        return "Xe máy"\n    return "Xe máy" if len(p) >= 5 and not p.startswith("0") else "Ô tô"\n\n'''
s=s.replace(needle,helper+needle)
# login audit
s=s.replace('''    return {"access_token": token_for(user), "token_type": "bearer",\n            "user": {"id": user.id, "username": user.username, "role": user.role, "full_name": user.full_name}}''','''    audit(db, user, "LOGIN", "Đăng nhập hệ thống")\n    db.commit()\n    return {"access_token": token_for(user), "token_type": "bearer",\n            "user": {"id": user.id, "username": user.username, "role": user.role, "full_name": user.full_name}}''')
# checkin use inferred if empty/invalid; audit
s=s.replace('''    if not plate: raise HTTPException(400, "Biển số không được trống")\n    active_vehicle_ids''','''    if not plate: raise HTTPException(400, "Biển số không được trống")\n    detected_type = infer_vehicle_type(plate)\n    vehicle_type = data.vehicle_type if data.vehicle_type in ("Xe máy", "Ô tô", "Xe đạp") else detected_type\n    active_vehicle_ids''')
s=s.replace('''        existing = Vehicle(license_plate=plate, vehicle_type=data.vehicle_type)''','''        existing = Vehicle(license_plate=plate, vehicle_type=vehicle_type)''')
s=s.replace('''        existing.vehicle_type = data.vehicle_type\n    record = ParkingRecord''','''        existing.vehicle_type = vehicle_type\n    record = ParkingRecord''')
s=s.replace('''    db.add(record); db.commit(); db.refresh(record)\n    return {"message": "Cho xe vào thành công", "record_id": record.id, "time_in": record.time_in.isoformat(), "slot": slot.name}''','''    db.add(record)\n    audit(db, user, "CHECKIN", f"{plate} → {slot.name} ({vehicle_type})")\n    db.commit(); db.refresh(record)\n    return {"message": "Cho xe vào thành công", "record_id": record.id, "time_in": record.time_in.isoformat(), "slot": slot.name, "vehicle_type": vehicle_type}''')
# checkout audit
s=s.replace('''    if slot: slot.status = "empty"\n    db.commit()\n    return {"message": "Cho xe ra thành công"''','''    if slot: slot.status = "empty"\n    vehicle = db.get(Vehicle, record.vehicle_id)\n    audit(db, user, "CHECKOUT", f"{vehicle.license_plate if vehicle else record.vehicle_id} → {fee:,.0f} VNĐ")\n    db.commit()\n    return {"message": "Cho xe ra thành công"''')
# history don't delete physically: add deleted flag? schema migration hard. Instead protect deletion by audit and retain? User asked prior delete feature. Keep actual deletion conflicts. We'll change delete history to archive via new model impossible relation. Could add is_deleted column to record; create_all won't alter existing. avoid.
# Add analytics endpoints before local_ai
marker='def local_ai(db: Session, question: str):\n'
endpoints='''@app.get("/api/activity")\ndef activity(limit: int = Query(20, ge=1, le=100), db: Session = Depends(get_db), user: User = Depends(current_user)):\n    rows = db.query(AuditLog, User).outerjoin(User, AuditLog.user_id == User.id).order_by(AuditLog.id.desc()).limit(limit).all()\n    return [{"id": a.id, "username": u.username if u else "system", "action": a.action, "detail": a.detail, "created_at": a.created_at.isoformat()} for a,u in rows]\n\n@app.get("/api/analytics")\ndef analytics(db: Session = Depends(get_db), user: User = Depends(current_user)):\n    today = now_vn().date()\n    start = datetime.combine(today, datetime.min.time())\n    end = start + timedelta(days=1)\n    ins = db.query(ParkingRecord).filter(ParkingRecord.time_in >= start, ParkingRecord.time_in < end).count()\n    outs = db.query(ParkingRecord).filter(ParkingRecord.time_out >= start, ParkingRecord.time_out < end).count()\n    revenue = db.query(func.coalesce(func.sum(ParkingRecord.fee), 0)).filter(ParkingRecord.time_out >= start, ParkingRecord.time_out < end).scalar() or 0\n    types = {}\n    for (typ, count) in db.query(Vehicle.vehicle_type, func.count(ParkingRecord.id)).join(ParkingRecord, ParkingRecord.vehicle_id == Vehicle.id).group_by(Vehicle.vehicle_type).all(): types[typ] = count\n    return {"today_checkins": ins, "today_checkouts": outs, "today_revenue": float(revenue), "vehicle_types": types}\n\n'''
s=s.replace(marker,endpoints+marker)
p.write_text(s)
